version: '3.9'
services:
  #Servicio para NodeJS
  app:
    container_name: t2-users
    build: . 
    ports:
      - 3000:3000  # Adjust the ports as needed
    volumes:
      - './:/usr/src/app'

  # dbsetup:
  #   image: postgres
  #   env_file: ./.env
  #   depends_on:
  #     - postgres
  #   restart: "no"
  #   volumes:
  #     - ./initdb:/var/local/initdb
  #   entrypoint: ["bash", "-c", "sleep 10 && cd /var/local/initdb && PGPASSWORD=$${POSTGRES_PASSWORD} POSTGRES_HOST_AUTH_METHOD=trust psql -h postgres -U $${POSTGRES_USER} -d $${POSTGRES_DB} -a -f migrations.sql"]
