version: '3.9'
services:
  #Servicio para NodeJS
  app:
    container_name: t2-users
    build: . 
    ports:
      - '8080:8080'  # Adjust the ports as needed
    volumes:
      - './:/usr/src/app'

  # Servicio para PostgreSQL
  postgres:
    image: postgres:latest
    container_name: t2-users-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "8081:8081"

  # Servicio para PgAdmin
  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: t2-users-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:8082"
