name: Deploy okteto
on:
  push:
    branches: [ "main", "development" ]

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Context Setup"
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Build"
        uses: okteto/build@latest
        with:
          tag: myapp-backend:latest
          file: Dockerfile
          path: backend
