name: Deploy okteto
on:
  push:
    branches: [ "main", "development" ]

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@master
    
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Create devlopment environments namespace"
      uses: okteto/namespace@latest
      with:
        namespace: snap-msg-auth-user-julianquino
